# Generated by Django 3.2.4 on 2021-07-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True, verbose_name='Class Name')),
                ('room_number', models.PositiveSmallIntegerField(default=0, verbose_name='Room Number')),
            ],
        ),
    ]
