# Generated by Django 3.2.4 on 2021-07-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('parents', '0002_rename_parents_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Age')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=50, null=True, verbose_name='Gender')),
                ('student_class', models.CharField(choices=[('six', '6th'), ('seven', '7th'), ('eight', '8th'), ('nine', '9th'), ('ten', '10th'), ('eleven', '11th'), ('twelve', '12th')], default='six', max_length=10, verbose_name='Student Class')),
                ('dob', models.DateField(verbose_name='D.O.B')),
                ('date_of_joined', models.DateField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.staff', verbose_name='Mentor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parents.parent', verbose_name='Parent')),
            ],
        ),
    ]
